pipeline {
  agent any
    
  tools {nodejs "nodejs"}
    
  stages {
    stage('Build') {
      steps {
        dir('backend'){
          sh 'npm install'
        }
      }
    }  
    stage('deploy to GCP') {
      steps {
        sshagent(['ssh-key']) {
            sh 'ssh -o StrictHostKeyChecking-no mukherjeeabhilash8@35.192.185.129'
        }
      }
    }
  }
}