pipeline {
  agent any
    
  tools {nodejs "nodejs"}
    
  stages {
    stage('Build') {
      steps {
        dir('backend'){
          sh 'npm install'
        }
      }
    }  
    stage('deploy to GCP') {
      steps {
        sshagent(credentials: ['ssh-key']) {
            sh "ssh -o StrictHostKeyChecking=no -l mukherjeeabhilash8 35.192.185.129 cd chat-application && cd backend && git pull origin dev"
        }
      }
    }
  }
}